
# Example usage
# $ docker run -it --net=host \
#   -e MONGODB_URI="mongodb://127.0.0.1:27017" \
#   docker-runner 3.5 argon

FROM centos:7 AS base
RUN yum update -y && yum install -y git make gcc gcc-c++

FROM base

WORKDIR /root
COPY entrypoint.sh entrypoint.sh

ARG MONGODB_URI
ARG DRIVER_VERSION

ENV NVM "--lts=argon"
ENV DRIVER_REVISION "master"
ENV DRIVER_REPOSITORY "https://github.com/mongodb/node-mongodb-native.git"

ENV NVM_DIR /root/.nvm
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.35.3/install.sh | bash \
    && . $NVM_DIR/nvm.sh

ENTRYPOINT ["/bin/bash", "/root/entrypoint.sh"]
CMD ["master", "dubnium"]
